import { freezeCatalog, type Camera } from "./catalog-types";

export const ANALOG_CAMERA_CATALOG = freezeCatalog([
  {
    id: "analog-camera-dh-hac-t1a21n-u-028b",
    brand: "Dahua",
    reference: "DH-HAC-T1A21N-U-028B",
    systemType: "analog",
    resolutionGroup: "2-mp",
    format: "Domo",
    description: "1080p; IR 25 m; plástica; interior",
    pricingStatus: "priced",
    salePriceCop: 90000,
    withAccessoriesSalePriceCop: 140000,
  },
  {
    id: "analog-camera-dh-hac-b1a21n-u-0280b",
    brand: "Dahua",
    reference: "DH-HAC-B1A21N-U-0280B",
    systemType: "analog",
    resolutionGroup: "2-mp",
    format: "Bala",
    description: "1080p; IR 30 m; IP67; plástica",
    pricingStatus: "priced",
    salePriceCop: 100000,
    withAccessoriesSalePriceCop: 150000,
  },
  {
    id: "analog-camera-dh-hac-hdw1200clqn-il-a-0280b",
    brand: "Dahua",
    reference: "DH-HAC-HDW1200CLQN-IL-A-0280B",
    systemType: "analog",
    resolutionGroup: "2-mp",
    format: "Domo",
    description: "Smart Dual + Full Color; IR 20 m; micrófono; IP67",
    pricingStatus: "priced",
    salePriceCop: 120000,
    withAccessoriesSalePriceCop: 170000,
  },
  {
    id: "analog-camera-dh-hac-hfw1200cln-il-a-0280b",
    brand: "Dahua",
    reference: "DH-HAC-HFW1200CLN-IL-A-0280B",
    systemType: "analog",
    resolutionGroup: "2-mp",
    format: "Bala",
    description: "Smart Dual Color; 2,8 mm; micrófono; IP67",
    pricingStatus: "priced",
    salePriceCop: 120000,
    withAccessoriesSalePriceCop: 170000,
  },
  {
    id: "analog-camera-dh-hac-hdw1200tlmn-il-a-0280b",
    brand: "Dahua",
    reference: "DH-HAC-HDW1200TLMN-IL-A-0280B",
    systemType: "analog",
    resolutionGroup: "2-mp",
    format: "Domo",
    description: "Smart Dual Full Color; 20 m; micrófono; semimetálica",
    pricingStatus: "priced",
    salePriceCop: 145000,
    withAccessoriesSalePriceCop: 195000,
  },
  {
    id: "analog-camera-dh-hac-hfw1200rn-z-ire6-s5",
    brand: "Dahua",
    reference: "DH-HAC-HFW1200RN-Z-IRE6-S5",
    systemType: "analog",
    resolutionGroup: "2-mp",
    format: "Bala",
    description: "Varifocal motorizada 2,7-12 mm; IR 60 m; IP67",
    pricingStatus: "priced",
    salePriceCop: 235000,
    withAccessoriesSalePriceCop: 285000,
  },
  {
    id: "analog-camera-ds-2ce56d0t-irpf-2-8mm-c",
    brand: "Hikvision",
    reference: "DS-2CE56D0T-IRPF(2.8mm)(C)",
    systemType: "analog",
    resolutionGroup: "2-mp",
    format: "Turret",
    description: "1080p; IR 20 m; plástica; interior",
    pricingStatus: "priced",
    salePriceCop: 105000,
    withAccessoriesSalePriceCop: 155000,
  },
  {
    id: "analog-camera-ds-2ce16d0t-irpf-2-8mm-c",
    brand: "Hikvision",
    reference: "DS-2CE16D0T-IRPF(2.8mm)(C)",
    systemType: "analog",
    resolutionGroup: "2-mp",
    format: "Bala",
    description: "1080p; IR 20 m; plástica",
    pricingStatus: "priced",
    salePriceCop: 125000,
    withAccessoriesSalePriceCop: 175000,
  },
  {
    id: "analog-camera-ds-2ce76d0t-lpfs-2-8mm",
    brand: "Hikvision",
    reference: "DS-2CE76D0T-LPFS(2.8mm)",
    systemType: "analog",
    resolutionGroup: "2-mp",
    format: "Turret",
    description: "1080p; audio coaxial; Smart IR 20 m; plástica",
    pricingStatus: "priced",
    salePriceCop: 135000,
    withAccessoriesSalePriceCop: 185000,
  },
  {
    id: "analog-camera-ds-2ce16d0t-lpfs-2-8mm-o-std",
    brand: "Hikvision",
    reference: "DS-2CE16D0T-LPFS(2.8mm)(O-STD)",
    systemType: "analog",
    resolutionGroup: "2-mp",
    format: "Mini bala",
    description: "Smart Hybrid Color; IR 25 m; IP67; plástica",
    pricingStatus: "priced",
    salePriceCop: 140000,
    withAccessoriesSalePriceCop: 190000,
  },
  {
    id: "analog-camera-ds-2ce70df0t-lpfs-2-8mm-o-std",
    brand: "Hikvision",
    reference: "DS-2CE70DF0T-LPFS(2.8mm)(O-STD)",
    systemType: "analog",
    resolutionGroup: "2-mp",
    format: "Domo",
    description: "ColorVu 24/7; luz blanca 20 m; audio; IP67",
    pricingStatus: "priced",
    salePriceCop: 155000,
    withAccessoriesSalePriceCop: 205000,
  },
  {
    id: "analog-camera-ds-2ce79d0t-vfit3f-2-7-13-5mm-c",
    brand: "Hikvision",
    reference: "DS-2CE79D0T-VFIT3F(2.7-13.5mm)(C)",
    systemType: "analog",
    resolutionGroup: "2-mp",
    format: "Turret",
    description: "Varifocal 2,7-13,5 mm; IR 40 m; IP67",
    pricingStatus: "priced",
    salePriceCop: 255000,
    withAccessoriesSalePriceCop: 305000,
  },
  {
    id: "analog-camera-thc-t120-pc-2-8mm",
    brand: "HiLook",
    reference: "THC-T120-PC (2.8mm)",
    systemType: "analog",
    resolutionGroup: "2-mp",
    format: "Turret",
    description: "1080p; IR 20 m; plástica; interior",
    pricingStatus: "priced",
    salePriceCop: 90000,
    withAccessoriesSalePriceCop: 140000,
  },
  {
    id: "analog-camera-thc-b120-pc-2-8mm",
    brand: "HiLook",
    reference: "THC-B120-PC (2.8mm)",
    systemType: "analog",
    resolutionGroup: "2-mp",
    format: "Bala",
    description: "1080p; IR 20 m; IP66; plástica",
    pricingStatus: "priced",
    salePriceCop: 95000,
    withAccessoriesSalePriceCop: 145000,
  },
  {
    id: "analog-camera-thc-t127-lps-2-8mm",
    brand: "HiLook",
    reference: "THC-T127-LPS(2.8mm)",
    systemType: "analog",
    resolutionGroup: "2-mp",
    format: "Turret",
    description: "Smart Hybrid Light; audio; IR 20 m",
    pricingStatus: "priced",
    salePriceCop: 120000,
    withAccessoriesSalePriceCop: 170000,
  },
  {
    id: "analog-camera-thc-t129-p-2-8mm",
    brand: "HiLook",
    reference: "THC-T129-P (2.8mm)",
    systemType: "analog",
    resolutionGroup: "2-mp",
    format: "Turret",
    description: "ColorVu 24/7; luz blanca 20 m; IP66; plástica",
    pricingStatus: "priced",
    salePriceCop: 120000,
    withAccessoriesSalePriceCop: 170000,
  },
  {
    id: "analog-camera-thc-b127-lps",
    brand: "HiLook",
    reference: "THC-B127-LPS",
    systemType: "analog",
    resolutionGroup: "2-mp",
    format: "Bala",
    description: "Smart Hybrid Light; audio; IR 20 m",
    pricingStatus: "priced",
    salePriceCop: 125000,
    withAccessoriesSalePriceCop: 175000,
  },
  {
    id: "analog-camera-thc-t320-vf-2-8-12mm",
    brand: "HiLook",
    reference: "THC-T320-VF (2.8-12mm)",
    systemType: "analog",
    resolutionGroup: "2-mp",
    format: "Turret",
    description: "Varifocal 2,8-12 mm; IR 40 m; IP66; semimetálica",
    pricingStatus: "priced",
    salePriceCop: 180000,
    withAccessoriesSalePriceCop: 230000,
  },
  {
    id: "analog-camera-dh-hac-t1a51n-u-0280b-s2",
    brand: "Dahua",
    reference: "DH-HAC-T1A51N-U-0280B-S2",
    systemType: "analog",
    resolutionGroup: "3k-5-mp",
    format: "Domo",
    description: "5 MP; IR 30 m; plástica",
    pricingStatus: "priced",
    salePriceCop: 110000,
    withAccessoriesSalePriceCop: 160000,
  },
  {
    id: "analog-camera-dh-hac-b1a51n-u-0280b-s2",
    brand: "Dahua",
    reference: "DH-HAC-B1A51N-U-0280B-S2",
    systemType: "analog",
    resolutionGroup: "3k-5-mp",
    format: "Bala",
    description: "5 MP; IR 30 m; IP67; plástica",
    pricingStatus: "priced",
    salePriceCop: 130000,
    withAccessoriesSalePriceCop: 180000,
  },
  {
    id: "analog-camera-dh-hac-t1a51n-u-a-0280b-s2",
    brand: "Dahua",
    reference: "DH-HAC-T1A51N-U-A-0280B-S2",
    systemType: "analog",
    resolutionGroup: "3k-5-mp",
    format: "Domo",
    description: "5 MP; IR 20 m; micrófono; plástica",
    pricingStatus: "priced",
    salePriceCop: 135000,
    withAccessoriesSalePriceCop: 185000,
  },
  {
    id: "analog-camera-dh-hac-b2a51n-u-0280b-s2",
    brand: "Dahua",
    reference: "DH-HAC-B2A51N-U-0280B-S2",
    systemType: "analog",
    resolutionGroup: "3k-5-mp",
    format: "Bala",
    description: "5 MP; IR 30 m; IP67; metálica",
    pricingStatus: "priced",
    salePriceCop: 150000,
    withAccessoriesSalePriceCop: 200000,
  },
  {
    id: "analog-camera-dh-hac-hfw1500rln-il-a-0280b",
    brand: "Dahua",
    reference: "DH-HAC-HFW1500RLN-IL-A-0280B",
    systemType: "analog",
    resolutionGroup: "3k-5-mp",
    format: "Bala",
    description: "5 MP; Smart Dual Light 30 m; micrófono; IP67",
    pricingStatus: "priced",
    salePriceCop: 160000,
    withAccessoriesSalePriceCop: 210000,
  },
  {
    id: "analog-camera-dh-hac-hdw1500tlmn-il-a-0280b",
    brand: "Dahua",
    reference: "DH-HAC-HDW1500TLMN-IL-A-0280B",
    systemType: "analog",
    resolutionGroup: "3k-5-mp",
    format: "Domo",
    description: "5 MP; Smart Dual Light 20 m; micrófono; semimetálica",
    pricingStatus: "priced",
    salePriceCop: 180000,
    withAccessoriesSalePriceCop: 230000,
  },
  {
    id: "analog-camera-ds-2ce76k0t-lpfs-2-8mm",
    brand: "Hikvision",
    reference: "DS-2CE76K0T-LPFS(2.8mm)",
    systemType: "analog",
    resolutionGroup: "3k-5-mp",
    format: "Turret",
    description: "3K; híbrida B/N-ColorVu; IR 20 m; audio; plástica",
    pricingStatus: "priced",
    salePriceCop: 180000,
    withAccessoriesSalePriceCop: 230000,
  },
  {
    id: "analog-camera-ds-2ce16k0t-lpfs-2-8mm",
    brand: "Hikvision",
    reference: "DS-2CE16K0T-LPFS(2.8mm)",
    systemType: "analog",
    resolutionGroup: "3k-5-mp",
    format: "Mini bala",
    description: "3K; híbrida; IR 25 m + luz 20 m; audio; IP67",
    pricingStatus: "priced",
    salePriceCop: 190000,
    withAccessoriesSalePriceCop: 240000,
  },
  {
    id: "analog-camera-ds-2ce17k0t-lfs-2-8mm",
    brand: "Hikvision",
    reference: "DS-2CE17K0T-LFS(2.8mm)",
    systemType: "analog",
    resolutionGroup: "3k-5-mp",
    format: "Bala",
    description: "3K; híbrida B/N-ColorVu; alcance 40 m; audio; IP67",
    pricingStatus: "priced",
    salePriceCop: 215000,
    withAccessoriesSalePriceCop: 265000,
  },
  {
    id: "analog-camera-ds-2ce70kf0t-pfs-2-8mm",
    brand: "Hikvision",
    reference: "DS-2CE70KF0T-PFS(2.8mm)",
    systemType: "analog",
    resolutionGroup: "3k-5-mp",
    format: "Turret",
    description: "3K; ColorVu; luz blanca 20 m; audio; plástica",
    pricingStatus: "priced",
    salePriceCop: 255000,
    withAccessoriesSalePriceCop: 305000,
  },
  {
    id: "analog-camera-ds-2ce10kf0t-fs-2-8mm",
    brand: "Hikvision",
    reference: "DS-2CE10KF0T-FS(2.8mm)",
    systemType: "analog",
    resolutionGroup: "3k-5-mp",
    format: "Bala",
    description: "3K; ColorVu; luz blanca 20 m; audio; IP67; metal",
    pricingStatus: "priced",
    salePriceCop: 280000,
    withAccessoriesSalePriceCop: 330000,
  },
  {
    id: "analog-camera-ds-2ce79h0t-it3zf-2-7-13-5mm-c",
    brand: "Hikvision",
    reference: "DS-2CE79H0T-IT3ZF(2.7-13.5mm)(C)",
    systemType: "analog",
    resolutionGroup: "3k-5-mp",
    format: "Domo",
    description: "5 MP; varifocal motorizada; IR 40 m; IP67; metal",
    pricingStatus: "priced",
    salePriceCop: 395000,
    withAccessoriesSalePriceCop: 445000,
  },
  {
    id: "analog-camera-thc-t150-p-2-8mm",
    brand: "HiLook",
    reference: "THC-T150-P (2.8mm)",
    systemType: "analog",
    resolutionGroup: "3k-5-mp",
    format: "Turret",
    description: "5 MP; IR 20 m; IP66; plástica",
    pricingStatus: "priced",
    salePriceCop: 125000,
    withAccessoriesSalePriceCop: 175000,
  },
  {
    id: "analog-camera-thc-b150-p-2-8mm",
    brand: "HiLook",
    reference: "THC-B150-P (2.8mm)",
    systemType: "analog",
    resolutionGroup: "3k-5-mp",
    format: "Mini bala",
    description: "5 MP; IR 20 m; IP66; plástica",
    pricingStatus: "priced",
    salePriceCop: 140000,
    withAccessoriesSalePriceCop: 190000,
  },
  {
    id: "analog-camera-thc-b159-ms-2-8mm",
    brand: "HiLook",
    reference: "THC-B159-MS(2.8mm)",
    systemType: "analog",
    resolutionGroup: "3k-5-mp",
    format: "Bala",
    description: "5 MP; ColorVu 24/7; luz blanca 20 m; IP66; metálica",
    pricingStatus: "priced",
    salePriceCop: 220000,
    withAccessoriesSalePriceCop: 270000,
  },
  {
    id: "analog-camera-dh-hac-hdw1801clqn-il-a-0280b-dip",
    brand: "Dahua",
    reference: "DH-HAC-HDW1801CLQN-IL-A-0280B-DIP",
    systemType: "analog",
    resolutionGroup: "8-mp-4k",
    format: "Turret",
    description: "8 MP / 4K; Smart Dual Light; micrófono",
    pricingStatus: "priced",
    salePriceCop: 195000,
    withAccessoriesSalePriceCop: 245000,
  },
  {
    id: "analog-camera-dh-hac-hfw1800rn-0280b",
    brand: "Dahua",
    reference: "DH-HAC-HFW1800RN-0280B",
    systemType: "analog",
    resolutionGroup: "8-mp-4k",
    format: "Bala",
    description: "4K; IR 20 m; IP50; plástica",
    pricingStatus: "priced",
    salePriceCop: 200000,
    withAccessoriesSalePriceCop: 250000,
  },
  {
    id: "analog-camera-dh-hac-hfw1801rln-il-t-0280-dip",
    brand: "Dahua",
    reference: "DH-HAC-HFW1801RLN-IL-T-0280-DIP",
    systemType: "analog",
    resolutionGroup: "8-mp-4k",
    format: "Bala",
    description: "8 MP; Smart Dual Light 30 m; audio bidireccional",
    pricingStatus: "priced",
    salePriceCop: 205000,
    withAccessoriesSalePriceCop: 255000,
  },
  {
    id: "analog-camera-dh-hac-hdw1801tlmn-il-a-0280b",
    brand: "Dahua",
    reference: "DH-HAC-HDW1801TLMN-IL-A-0280B",
    systemType: "analog",
    resolutionGroup: "8-mp-4k",
    format: "Turret",
    description: "4K / 8 MP; Smart Dual Light; IR 30 m; micrófono",
    pricingStatus: "priced",
    salePriceCop: 220000,
    withAccessoriesSalePriceCop: 270000,
  },
  {
    id: "analog-camera-dh-hac-hfw1801tlmn-il-a-0280b",
    brand: "Dahua",
    reference: "DH-HAC-HFW1801TLMN-IL-A-0280B",
    systemType: "analog",
    resolutionGroup: "8-mp-4k",
    format: "Bala",
    description: "4K / 8 MP; Smart Dual Light; IR 40 m; micrófono",
    pricingStatus: "priced",
    salePriceCop: 245000,
    withAccessoriesSalePriceCop: 295000,
  },
  {
    id: "analog-camera-dh-hac-hdw1800tln-a-0280b",
    brand: "Dahua",
    reference: "DH-HAC-HDW1800TLN-A-0280B",
    systemType: "analog",
    resolutionGroup: "8-mp-4k",
    format: "Domo",
    description: "4K a 15 fps; IR 30 m; IP67; micrófono",
    pricingStatus: "priced",
    salePriceCop: 255000,
    withAccessoriesSalePriceCop: 305000,
  },
  {
    id: "analog-camera-ds-2ce76u1t-itpf-2-8mm",
    brand: "Hikvision",
    reference: "DS-2CE76U1T-ITPF(2.8mm)",
    systemType: "analog",
    resolutionGroup: "8-mp-4k",
    format: "Turret",
    description: "8 MP; IR 30 m; IP67; plástica",
    pricingStatus: "priced",
    salePriceCop: 280000,
    withAccessoriesSalePriceCop: 330000,
  },
  {
    id: "analog-camera-ds-2ce16u1t-itpf-2-8mm",
    brand: "Hikvision",
    reference: "DS-2CE16U1T-ITPF(2.8mm)",
    systemType: "analog",
    resolutionGroup: "8-mp-4k",
    format: "Bala",
    description: "8 MP; IR 30 m; IP67; plástica",
    pricingStatus: "priced",
    salePriceCop: 310000,
    withAccessoriesSalePriceCop: 360000,
  },
  {
    id: "analog-camera-ds-2ce57u1t-vpitf-3-6mm",
    brand: "Hikvision",
    reference: "DS-2CE57U1T-VPITF(3.6mm)",
    systemType: "analog",
    resolutionGroup: "8-mp-4k",
    format: "Domo",
    description: "8 MP; IR 30 m; IK10; metálica",
    pricingStatus: "priced",
    salePriceCop: 365000,
    withAccessoriesSalePriceCop: 415000,
  },
  {
    id: "analog-camera-ds-2ce10uf3t-e-2-8mm",
    brand: "Hikvision",
    reference: "DS-2CE10UF3T-E(2.8mm)",
    systemType: "analog",
    resolutionGroup: "8-mp-4k",
    format: "Bala",
    description: "4K ColorVu; luz blanca 20 m; IP67; metálica",
    pricingStatus: "priced",
    salePriceCop: 530000,
    withAccessoriesSalePriceCop: 580000,
  },
  {
    id: "analog-camera-ds-2ce72uf3t-e-2-8mm",
    brand: "Hikvision",
    reference: "DS-2CE72UF3T-E(2.8mm)",
    systemType: "analog",
    resolutionGroup: "8-mp-4k",
    format: "Turret",
    description: "4K ColorVu; luz blanca 40 m; WDR 130 dB; IP67",
    pricingStatus: "priced",
    salePriceCop: 560000,
    withAccessoriesSalePriceCop: 610000,
  },
  {
    id: "analog-camera-ds-2ce79u1t-it3zf-2-7-13-5mm",
    brand: "Hikvision",
    reference: "DS-2CE79U1T-IT3ZF(2.7-13.5mm)",
    systemType: "analog",
    resolutionGroup: "8-mp-4k",
    format: "Turret",
    description: "8 MP; varifocal motorizada; IR 60 m; IP67; metal",
    pricingStatus: "priced",
    salePriceCop: 590000,
    withAccessoriesSalePriceCop: 640000,
  },
] as const satisfies readonly Camera[]);

// Availability notice, deliberately outside the product catalog.
export const ANALOG_CAMERA_AVAILABILITY_NOTICES = freezeCatalog([
  {
    id: "analog-hilook-8-mp-4k-unpublished",
    systemType: "analog",
    brand: "HiLook",
    resolutionGroup: "8-mp-4k",
    reference: null,
    pricingStatus: "manual-confirmation",
    salePriceCop: null,
    withAccessoriesSalePriceCop: null,
    description: "Sin referencia ni precio de venta publicados.",
  },
] as const);
