import { freezeCatalog, type Recorder } from "./catalog-types";

export const DVR_XVR_CATALOG = freezeCatalog([
  {
    id: "dvr-xvr-dh-xvr1b04-i-t",
    brand: "Dahua",
    reference: "DH-XVR1B04-I-T",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 4,
    description: "1080p; 4 + 1 IP; audio bidireccional; 1 SATA; H.265+",
    pricingStatus: "priced",
    salePriceCop: 210000,
  },
  {
    id: "dvr-xvr-dh-xvr1b04h-i-t",
    brand: "Dahua",
    reference: "DH-XVR1B04H-I-T",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 4,
    description: "Hasta 5 MP Lite; 4 + 2 IP; audio bidireccional",
    pricingStatus: "priced",
    salePriceCop: 275000,
  },
  {
    id: "dvr-xvr-dh-xvr5104hs-4kl-i3",
    brand: "Dahua",
    reference: "DH-XVR5104HS-4KL-I3",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 4,
    description: "Hasta 4K; 4 + 4 IP; 1 SATA; reconocimiento facial",
    pricingStatus: "priced",
    salePriceCop: 485000,
  },
  {
    id: "dvr-xvr-ds-7104hghi-m1-t",
    brand: "Hikvision",
    reference: "DS-7104HGHI-M1/T",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 4,
    description: "1080p / 2 MP Lite; audio bidireccional",
    pricingStatus: "priced",
    salePriceCop: 235000,
  },
  {
    id: "dvr-xvr-ids-7104hqhi-m1-s-c",
    brand: "Hikvision",
    reference: "iDS-7104HQHI-M1/S(C)",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 4,
    description: "5 MP Lite; capacidad indicada 10 TB; H.265+; AcuSense",
    pricingStatus: "priced",
    salePriceCop: 330000,
  },
  {
    id: "dvr-xvr-dvr-104g-m1-c",
    brand: "HiLook",
    reference: "DVR-104G-M1(C)",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 4,
    description: "1080p Lite; capacidad indicada 4 TB; H.265+; AcuSense",
    pricingStatus: "priced",
    salePriceCop: 220000,
  },
  {
    id: "dvr-xvr-dvr-204u-m1",
    brand: "HiLook",
    reference: "DVR-204U-M1",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 4,
    description: "5 MP; 1 bahía / 10 TB; H.265+; 8 fps; AcuSense",
    pricingStatus: "priced",
    salePriceCop: 515000,
  },
  {
    id: "dvr-xvr-dh-xvr1b08-i-t",
    brand: "Dahua",
    reference: "DH-XVR1B08-I-T",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 8,
    description: "1080p; 8 + 2 IP; audio bidireccional; H.265+",
    pricingStatus: "priced",
    salePriceCop: 250000,
  },
  {
    id: "dvr-xvr-dh-xvr1b08h-i-t",
    brand: "Dahua",
    reference: "DH-XVR1B08H-I-T",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 8,
    description: "Hasta 5 MP Lite; 8 + 4 IP; audio bidireccional",
    pricingStatus: "priced",
    salePriceCop: 405000,
  },
  {
    id: "dvr-xvr-dh-xvr5108hs-4kl-i3-t",
    brand: "Dahua",
    reference: "DH-XVR5108HS-4KL-I3-T",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 8,
    description: "Hasta 4K CVI o 5 MP TVI; 8 + 4 IP; audio bidireccional",
    pricingStatus: "priced",
    salePriceCop: 1050000,
  },
  {
    id: "dvr-xvr-ds-7108hghi-m1-t",
    brand: "Hikvision",
    reference: "DS-7108HGHI-M1/T",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 8,
    description: "1080p Lite; 1 bahía / 4 TB; H.265+; AcuSense",
    pricingStatus: "priced",
    salePriceCop: 300000,
  },
  {
    id: "dvr-xvr-ids-7108hqhi-m1-s-c",
    brand: "Hikvision",
    reference: "iDS-7108HQHI-M1/S(C)",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 8,
    description: "5 MP Lite; capacidad indicada 10 TB; analíticas; AcuSense",
    pricingStatus: "priced",
    salePriceCop: 485000,
  },
  {
    id: "dvr-xvr-ids-7208huhi-m1-xt",
    brand: "Hikvision",
    reference: "iDS-7208HUHI-M1/XT",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 8,
    description: "4K / 8 MP; 8 + 8 IP; audio bidireccional; AcuSense",
    pricingStatus: "priced",
    salePriceCop: 930000,
  },
  {
    id: "dvr-xvr-dvr-108g-m1-c",
    brand: "HiLook",
    reference: "DVR-108G-M1(C)",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 8,
    description: "1080p Lite; capacidad indicada 4 TB; H.265+; AcuSense",
    pricingStatus: "priced",
    salePriceCop: 270000,
  },
  {
    id: "dvr-xvr-dvr-208q-m1-c-la",
    brand: "HiLook",
    reference: "DVR-208Q-M1(C)/LA",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 8,
    description: "Hasta 4 MP Lite; 10 TB; H.265+; 15 fps; AcuSense",
    pricingStatus: "priced",
    salePriceCop: 445000,
  },
  {
    id: "dvr-xvr-dvr-208u-m1",
    brand: "HiLook",
    reference: "DVR-208U-M1",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 8,
    description: "8 MP; 1 bahía / 10 TB; H.265+; 8 fps; AcuSense",
    pricingStatus: "priced",
    salePriceCop: 790000,
  },
  {
    id: "dvr-xvr-dh-xvr1b16-i-t",
    brand: "Dahua",
    reference: "DH-XVR1B16-I-T",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 16,
    description: "Hasta 1080p / 2 MP; audio bidireccional",
    pricingStatus: "priced",
    salePriceCop: 405000,
  },
  {
    id: "dvr-xvr-dh-xvr1b16h-i-t",
    brand: "Dahua",
    reference: "DH-XVR1B16H-I-T",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 16,
    description: "Hasta 5 MP Lite; 16 + 8 IP; audio bidireccional",
    pricingStatus: "priced",
    salePriceCop: 680000,
  },
  {
    id: "dvr-xvr-dhi-xvr5116h-4kl-i3-v2",
    brand: "Dahua",
    reference: "DHI-XVR5116H-4KL-I3-V2",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 16,
    description: "Hasta 4K; 16 + 16 IP; 1 SATA; WizSense",
    pricingStatus: "priced",
    salePriceCop: 1450000,
  },
  {
    id: "dvr-xvr-ds-7116hghi-m1-c",
    brand: "Hikvision",
    reference: "DS-7116HGHI-M1(C)",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 16,
    description: "1080p; capacidad indicada 10 TB; 15 fps; AcuSense",
    pricingStatus: "priced",
    salePriceCop: 520000,
  },
  {
    id: "dvr-xvr-ids-7116hqhi-m1-s-c",
    brand: "Hikvision",
    reference: "iDS-7116HQHI-M1/S(C)",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 16,
    description: "5 MP Lite; capacidad indicada 10 TB; H.265 Pro+; AcuSense",
    pricingStatus: "priced",
    salePriceCop: 730000,
  },
  {
    id: "dvr-xvr-ids-7216huhi-m2-xt",
    brand: "Hikvision",
    reference: "iDS-7216HUHI-M2/XT",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 16,
    description: "4K / 8 MP; 16 + 16 IP; audio bidireccional; 2 bahías",
    pricingStatus: "priced",
    salePriceCop: 2020000,
  },
  {
    id: "dvr-xvr-dvr-116g-m1-c",
    brand: "HiLook",
    reference: "DVR-116G-M1(C)",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 16,
    description: "1080p Lite; capacidad indicada 10 TB; H.265+; AcuSense",
    pricingStatus: "priced",
    salePriceCop: 425000,
  },
  {
    id: "dvr-xvr-dvr-216q-m1",
    brand: "HiLook",
    reference: "DVR-216Q-M1",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 16,
    description: "Hasta 4 MP Lite; 1 bahía / 10 TB; 4 IP; AcuSense",
    pricingStatus: "priced",
    salePriceCop: 700000,
  },
  {
    id: "dvr-xvr-dvr-216u-m2-c-la",
    brand: "HiLook",
    reference: "DVR-216U-M2(C)/LA",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 16,
    description: "8 MP; capacidad indicada 10 TB; H.265+; 8 fps; AcuSense",
    pricingStatus: "priced",
    salePriceCop: 1520000,
  },
  {
    id: "dvr-xvr-dh-xvr4232an-i-t",
    brand: "Dahua",
    reference: "DH-XVR4232AN-I-T",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 32,
    description: "Hasta 1080N; 32 + 4 IP; H.265+; WizSense",
    pricingStatus: "priced",
    salePriceCop: 1050000,
  },
  {
    id: "dvr-xvr-dh-xvr5232an-i3-t",
    brand: "Dahua",
    reference: "DH-XVR5232AN-I3-T",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 32,
    description: "Hasta 5M-N; IP hasta 6 MP; 2 SATA / 10 TB",
    pricingStatus: "priced",
    salePriceCop: 1580000,
  },
  {
    id: "dvr-xvr-ds-7232hghi-m2",
    brand: "Hikvision",
    reference: "DS-7232HGHI-M2",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 32,
    description: "1080p Lite; capacidad indicada 10 TB; 15 fps; AcuSense",
    pricingStatus: "priced",
    salePriceCop: 1150000,
  },
  {
    id: "dvr-xvr-ids-7232hqhi-m2-xt-std",
    brand: "Hikvision",
    reference: "iDS-7232HQHI-M2/XT(STD)",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 32,
    description: "5 MP Lite / 3K Lite; 32 + 8 IP; 2 bahías",
    pricingStatus: "priced",
    salePriceCop: 1750000,
  },
  {
    id: "dvr-xvr-ids-7332huhi-m4-s",
    brand: "Hikvision",
    reference: "iDS-7332HUHI-M4/S",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 32,
    description: "8 MP; capacidad indicada 12 TB; 8 a 12 fps; AcuSense",
    pricingStatus: "priced",
    salePriceCop: 4300000,
  },
  {
    id: "dvr-xvr-dvr-232q-m2",
    brand: "HiLook",
    reference: "DVR-232Q-M2",
    recorderType: "dvr-xvr",
    systemType: "analog",
    channels: 32,
    description: "Hasta 4 MP Lite; 2 bahías / 10 TB cada una; 4K HDMI",
    pricingStatus: "priced",
    salePriceCop: 1470000,
  },
] as const satisfies readonly Recorder[]);
