import { freezeCatalog, type ExteriorCable } from "./catalog-types";

export const EXTERIOR_CABLE_CATALOG = freezeCatalog([
  {
    id: "exterior-cable-utpcat5ex100",
    reference: "UTPCAT5EX100",
    category: "cat-5e",
    presentationLengthMeters: 100,
    construction: "Exterior; doble chaqueta; aleación 70-30",
    pricingStatus: "priced",
    salePriceCop: 70000,
  },
  {
    id: "exterior-cable-utpcat5ex",
    reference: "UTPCAT5EX",
    category: "cat-5e",
    presentationLengthMeters: 305,
    construction: "Exterior; doble chaqueta; aleación 70-30",
    pricingStatus: "priced",
    salePriceCop: 175000,
  },
  {
    id: "exterior-cable-utpcat6ex100",
    reference: "UTPCAT6EX100",
    category: "cat-6",
    presentationLengthMeters: 100,
    construction: "Exterior; doble chaqueta; aleación 70-30",
    pricingStatus: "priced",
    salePriceCop: 85000,
  },
  {
    id: "exterior-cable-utpcat6exenerline",
    reference: "UTPCAT6EXENERLINE",
    category: "cat-6",
    presentationLengthMeters: 305,
    construction: "Exterior Enerline; doble chaqueta; aleación 70-30",
    pricingStatus: "priced",
    salePriceCop: 250000,
  },
  {
    id: "exterior-cable-utpcat6exlps",
    reference: "UTPCAT6EXLPS",
    category: "cat-6",
    presentationLengthMeters: 305,
    construction: "Exterior LPS; doble chaqueta; aleación 70-30",
    pricingStatus: "priced",
    salePriceCop: 220000,
  },
  {
    id: "exterior-cable-utpcat5exco100",
    reference: "UTPCAT5EXCO100",
    category: "cat-5e",
    presentationLengthMeters: 100,
    construction: "Exterior; 100% cobre",
    pricingStatus: "priced",
    salePriceCop: 205000,
  },
  {
    id: "exterior-cable-utpcat6exco100",
    reference: "UTPCAT6EXCO100",
    category: "cat-6",
    presentationLengthMeters: 100,
    construction: "Exterior; 100% cobre",
    pricingStatus: "priced",
    salePriceCop: 245000,
  },
  {
    id: "exterior-cable-utpcat5exco",
    reference: "UTPCAT5EXCO",
    category: "cat-5e",
    presentationLengthMeters: 305,
    construction: "Exterior; 100% cobre",
    pricingStatus: "priced",
    salePriceCop: 525000,
  },
  {
    id: "exterior-cable-utpcat6exco",
    reference: "UTPCAT6EXCO",
    category: "cat-6",
    presentationLengthMeters: 305,
    construction: "Exterior; 100% cobre",
    pricingStatus: "priced",
    salePriceCop: 655000,
  },
] as const satisfies readonly ExteriorCable[]);
