import { freezeCatalog, type HardDrive } from "./catalog-types";

export const HARD_DRIVE_CATALOG = freezeCatalog([
  {
    id: "hard-drive-wd10pur",
    line: "Western Purple",
    reference: "WD10PUR",
    capacity: 1,
    capacityUnit: "TB",
    conditionAndWarranty: "Pull remanufacturado; 1 año de garantía directa",
    pricingStatus: "priced",
    salePriceCop: 460000,
  },
  {
    id: "hard-drive-wd20pur",
    line: "Western Purple",
    reference: "WD20PUR",
    capacity: 2,
    capacityUnit: "TB",
    conditionAndWarranty: "Purple; 3 años de garantía",
    pricingStatus: "priced",
    salePriceCop: 740000,
  },
  {
    id: "hard-drive-wd40pur",
    line: "Western Purple",
    reference: "WD40PUR",
    capacity: 4,
    capacityUnit: "TB",
    conditionAndWarranty: "Purple; 3 años de garantía",
    pricingStatus: "priced",
    salePriceCop: 900000,
  },
  {
    id: "hard-drive-wd60pur",
    line: "Western Purple",
    reference: "WD60PUR",
    capacity: 6,
    capacityUnit: "TB",
    conditionAndWarranty: "Purple; 3 años de garantía",
    pricingStatus: "manual-confirmation",
    salePriceCop: null,
  },
  {
    id: "hard-drive-wd80pur",
    line: "Western Purple",
    reference: "WD80PUR",
    capacity: 8,
    capacityUnit: "TB",
    conditionAndWarranty: "Purple; 3 años de garantía",
    pricingStatus: "manual-confirmation",
    salePriceCop: null,
  },
  {
    id: "hard-drive-wd100purz",
    line: "Western Purple",
    reference: "WD100PURZ",
    capacity: 10,
    capacityUnit: "TB",
    conditionAndWarranty: "Purple; 3 años de garantía",
    pricingStatus: "manual-confirmation",
    salePriceCop: null,
  },
  {
    id: "hard-drive-black1t",
    line: "Western Black",
    reference: "BLACK1T",
    capacity: 1,
    capacityUnit: "TB",
    conditionAndWarranty: "Nuevo; 1 año de garantía",
    pricingStatus: "priced",
    salePriceCop: 315000,
  },
  {
    id: "hard-drive-dpull500",
    line: "Pull",
    reference: "DPULL500",
    capacity: 500,
    capacityUnit: "GB",
    conditionAndWarranty: "Pull remanufacturado multimarca; 6 meses",
    pricingStatus: "priced",
    salePriceCop: 135000,
  },
  {
    id: "hard-drive-dpull1tr",
    line: "Pull",
    reference: "DPULL1TR",
    capacity: 1,
    capacityUnit: "TB",
    conditionAndWarranty: "Pull remanufacturado; 6 meses",
    pricingStatus: "priced",
    salePriceCop: 225000,
  },
  {
    id: "hard-drive-dpull2tr",
    line: "Pull",
    reference: "DPULL2TR",
    capacity: 2,
    capacityUnit: "TB",
    conditionAndWarranty: "Pull remanufacturado; 6 meses",
    pricingStatus: "priced",
    salePriceCop: 515000,
  },
  {
    id: "hard-drive-dpull3tr",
    line: "Pull",
    reference: "DPULL3TR",
    capacity: 3,
    capacityUnit: "TB",
    conditionAndWarranty: "Pull remanufacturado; 6 meses",
    pricingStatus: "priced",
    salePriceCop: 560000,
  },
  {
    id: "hard-drive-dpull4tr",
    line: "Pull",
    reference: "DPULL4TR",
    capacity: 4,
    capacityUnit: "TB",
    conditionAndWarranty: "Pull remanufacturado; 6 meses",
    pricingStatus: "priced",
    salePriceCop: 700000,
  },
] as const satisfies readonly HardDrive[]);
