import { freezeCatalog, type Camera } from "./catalog-types";

export const IP_CAMERA_CATALOG = freezeCatalog([
  {
    id: "ip-camera-dh-ipc-hfw1239s1p-a-il-0280b",
    brand: "Dahua",
    reference: "DH-IPC-HFW1239S1P-A-IL-0280B",
    systemType: "ip",
    resolutionGroup: "2-mp",
    format: "Bala",
    description: "2 MP; Smart Dual Light; micrófono; IR 30 m; IP67",
    pricingStatus: "priced",
    salePriceCop: 235000,
    withAccessoriesSalePriceCop: 260000,
  },
  {
    id: "ip-camera-dh-ipc-hfw1239tl1p-a-il-0280b",
    brand: "Dahua",
    reference: "DH-IPC-HFW1239TL1P-A-IL-0280B",
    systemType: "ip",
    resolutionGroup: "2-mp",
    format: "Bala",
    description: "2 MP; Smart Dual Light; micrófono; IR 40 m; IP67",
    pricingStatus: "priced",
    salePriceCop: 245000,
    withAccessoriesSalePriceCop: 270000,
  },
  {
    id: "ip-camera-dh-ipc-hdw1239v-a-il-0280b",
    brand: "Dahua",
    reference: "DH-IPC-HDW1239V-A-IL-0280B",
    systemType: "ip",
    resolutionGroup: "2-mp",
    format: "Domo",
    description: "2 MP; Smart Dual Light; micrófono; PoE; LED 30 m; IP67",
    pricingStatus: "priced",
    salePriceCop: 270000,
    withAccessoriesSalePriceCop: 295000,
  },
  {
    id: "ip-camera-dh-ipc-hdw1239t1p-a-il-0280b",
    brand: "Dahua",
    reference: "DH-IPC-HDW1239T1P-A-IL-0280B",
    systemType: "ip",
    resolutionGroup: "2-mp",
    format: "Domo",
    description: "2 MP; Smart Dual Light; micrófono; PoE; IR 30 m; IP67",
    pricingStatus: "priced",
    salePriceCop: 230000,
    withAccessoriesSalePriceCop: 255000,
  },
  {
    id: "ip-camera-ds-2cd1023g2-liu-2-8mm",
    brand: "Hikvision",
    reference: "DS-2CD1023G2-LIU(2.8mm)",
    systemType: "ip",
    resolutionGroup: "2-mp",
    format: "Bala",
    description: "2 MP; híbrida B/N-ColorVu; micrófono; IR 30 m; IP67",
    pricingStatus: "priced",
    salePriceCop: 275000,
    withAccessoriesSalePriceCop: 300000,
  },
  {
    id: "ip-camera-ds-2cd2021g1-i-2-8mm-c",
    brand: "Hikvision",
    reference: "DS-2CD2021G1-I(2.8mm)(C)",
    systemType: "ip",
    resolutionGroup: "2-mp",
    format: "Bala",
    description: "2 MP; H.265+; IR 30 m; semimetálica",
    pricingStatus: "priced",
    salePriceCop: 405000,
    withAccessoriesSalePriceCop: 430000,
  },
  {
    id: "ip-camera-ds-2cd1323g2-i-2-8mm",
    brand: "Hikvision",
    reference: "DS-2CD1323G2-I(2.8mm)",
    systemType: "ip",
    resolutionGroup: "2-mp",
    format: "Domo",
    description: "2 MP; H.265+; WDR; IR 40 m; IP67; IK10",
    pricingStatus: "priced",
    salePriceCop: 250000,
    withAccessoriesSalePriceCop: 275000,
  },
  {
    id: "ip-camera-ds-2cd1323g2-iuf-2-8mm",
    brand: "Hikvision",
    reference: "DS-2CD1323G2-IUF(2.8mm)",
    systemType: "ip",
    resolutionGroup: "2-mp",
    format: "Turret",
    description: "2 MP; micrófono; H.265+; IR 30 m; IP66; microSD",
    pricingStatus: "priced",
    salePriceCop: 260000,
    withAccessoriesSalePriceCop: 285000,
  },
  {
    id: "ip-camera-ds-2cd1123g2-liu-2-8mm",
    brand: "Hikvision",
    reference: "DS-2CD1123G2-LIU(2.8mm)",
    systemType: "ip",
    resolutionGroup: "2-mp",
    format: "Domo",
    description: "2 MP; híbrida; micrófono; IR 30 m; luz 20 m; IP67",
    pricingStatus: "priced",
    salePriceCop: 305000,
    withAccessoriesSalePriceCop: 330000,
  },
  {
    id: "ip-camera-ds-2cd1623g2-iz-2-8-12mm",
    brand: "Hikvision",
    reference: "DS-2CD1623G2-IZ(2.8-12mm)",
    systemType: "ip",
    resolutionGroup: "2-mp",
    format: "Bala",
    description: "2 MP; varifocal motorizada; H.265+; IR 50 m; IP67",
    pricingStatus: "priced",
    salePriceCop: 510000,
    withAccessoriesSalePriceCop: 535000,
  },
  {
    id: "ip-camera-ipc-b121h-2-8mm-c",
    brand: "HiLook",
    reference: "IPC-B121H (2.8mm)(C)",
    systemType: "ip",
    resolutionGroup: "2-mp",
    format: "Bala",
    description: "2 MP; H.265+; PoE; IR 30 m; IP67; semimetálica",
    pricingStatus: "priced",
    salePriceCop: 210000,
    withAccessoriesSalePriceCop: 235000,
  },
  {
    id: "ip-camera-ipc-t221h-2-8mm-c",
    brand: "HiLook",
    reference: "IPC-T221H (2.8mm)(C)",
    systemType: "ip",
    resolutionGroup: "2-mp",
    format: "Turret",
    description: "2 MP; H.265+; PoE; IR 30 m; IP67; semimetálica",
    pricingStatus: "priced",
    salePriceCop: 220000,
    withAccessoriesSalePriceCop: 245000,
  },
  {
    id: "ip-camera-ipc-d121h-2-8mm-c",
    brand: "HiLook",
    reference: "IPC-D121H (2.8mm)(C)",
    systemType: "ip",
    resolutionGroup: "2-mp",
    format: "Domo",
    description: "2 MP; H.265+; PoE; IR 30 m; IP67; IK10",
    pricingStatus: "priced",
    salePriceCop: 235000,
    withAccessoriesSalePriceCop: 260000,
  },
  {
    id: "ip-camera-ipc-b620h-z-2-8-12mm",
    brand: "HiLook",
    reference: "IPC-B620H-Z(2.8-12mm)",
    systemType: "ip",
    resolutionGroup: "2-mp",
    format: "Bala",
    description: "2 MP; varifocal motorizada; H.265+; IR 30 m; IP67",
    pricingStatus: "priced",
    salePriceCop: 390000,
    withAccessoriesSalePriceCop: 415000,
  },
  {
    id: "ip-camera-dh-ipc-hfw1439s1-a-il-0280b-s6",
    brand: "Dahua",
    reference: "DH-IPC-HFW1439S1-A-IL-0280B-S6",
    systemType: "ip",
    resolutionGroup: "4-mp",
    format: "Bala",
    description: "4 MP; Smart Dual Light; micrófono; 2,8 mm; IR 15 m",
    pricingStatus: "priced",
    salePriceCop: 300000,
    withAccessoriesSalePriceCop: 325000,
  },
  {
    id: "ip-camera-dh-ipc-hfw1439tl1p-a-il-0280b",
    brand: "Dahua",
    reference: "DH-IPC-HFW1439TL1P-A-IL-0280B",
    systemType: "ip",
    resolutionGroup: "4-mp",
    format: "Bala",
    description: "4 MP; Smart Dual Light; micrófono; 2,8 mm; IR 30 m",
    pricingStatus: "priced",
    salePriceCop: 325000,
    withAccessoriesSalePriceCop: 350000,
  },
  {
    id: "ip-camera-dh-ipc-hdw1439t1-a-il-0280b-s6",
    brand: "Dahua",
    reference: "DH-IPC-HDW1439T1-A-IL-0280B-S6",
    systemType: "ip",
    resolutionGroup: "4-mp",
    format: "Domo",
    description: "4 MP; Smart Dual Light; micrófono; 2,8 mm; IR 30 m",
    pricingStatus: "priced",
    salePriceCop: 305000,
    withAccessoriesSalePriceCop: 330000,
  },
  {
    id: "ip-camera-ds-2cd1043g2-liu-2-8mm",
    brand: "Hikvision",
    reference: "DS-2CD1043G2-LIU(2.8mm)",
    systemType: "ip",
    resolutionGroup: "4-mp",
    format: "Bala",
    description: "4 MP; híbrida B/N-ColorVu; micrófono; IR 30 m; IP67",
    pricingStatus: "priced",
    salePriceCop: 395000,
    withAccessoriesSalePriceCop: 420000,
  },
  {
    id: "ip-camera-ds-2cd1343g2-liuf",
    brand: "Hikvision",
    reference: "DS-2CD1343G2-LIUF",
    systemType: "ip",
    resolutionGroup: "4-mp",
    format: "Turret",
    description: "4 MP; luz híbrida; micrófono; IR 30 m; 2,8 mm",
    pricingStatus: "priced",
    salePriceCop: 390000,
    withAccessoriesSalePriceCop: 415000,
  },
  {
    id: "ip-camera-ds-2cd1047g2-l-2-8mm",
    brand: "Hikvision",
    reference: "DS-2CD1047G2-L(2.8mm)",
    systemType: "ip",
    resolutionGroup: "4-mp",
    format: "Bala",
    description: "4 MP; ColorVu; H.265+; WDR; IR 30 m; IP67",
    pricingStatus: "priced",
    salePriceCop: 435000,
    withAccessoriesSalePriceCop: 460000,
  },
  {
    id: "ip-camera-ds-2cd1347g2-luf-2-8mm",
    brand: "Hikvision",
    reference: "DS-2CD1347G2-LUF(2.8mm)",
    systemType: "ip",
    resolutionGroup: "4-mp",
    format: "Turret",
    description: "4 MP; ColorVu; audio; luz blanca 30 m; IP67",
    pricingStatus: "priced",
    salePriceCop: 485000,
    withAccessoriesSalePriceCop: 510000,
  },
  {
    id: "ip-camera-ds-2cd2043g2-i-2-8mm",
    brand: "Hikvision",
    reference: "DS-2CD2043G2-I(2.8mm)",
    systemType: "ip",
    resolutionGroup: "4-mp",
    format: "Bala",
    description: "4 MP; H.265+; IR 40 m; IP67; AcuSense",
    pricingStatus: "priced",
    salePriceCop: 580000,
    withAccessoriesSalePriceCop: 605000,
  },
  {
    id: "ip-camera-ds-2cd1743g2-iz-2-8-12mm",
    brand: "Hikvision",
    reference: "DS-2CD1743G2-IZ(2.8-12mm)",
    systemType: "ip",
    resolutionGroup: "4-mp",
    format: "Domo",
    description: "4 MP; varifocal motorizada; H.265+; IR 30 m; IP67",
    pricingStatus: "priced",
    salePriceCop: 630000,
    withAccessoriesSalePriceCop: 655000,
  },
  {
    id: "ip-camera-ipc-t240h-2-8mm-c",
    brand: "HiLook",
    reference: "IPC-T240H (2.8mm)(C)",
    systemType: "ip",
    resolutionGroup: "4-mp",
    format: "Turret",
    description: "4 MP; H.265+; PoE; IR 30 m; IP67; IK10",
    pricingStatus: "priced",
    salePriceCop: 320000,
    withAccessoriesSalePriceCop: 345000,
  },
  {
    id: "ip-camera-ipc-b140h-2-8mm-c",
    brand: "HiLook",
    reference: "IPC-B140H (2.8mm)(C)",
    systemType: "ip",
    resolutionGroup: "4-mp",
    format: "Bala",
    description: "4 MP; H.265+; PoE; IR 30 m; IP67",
    pricingStatus: "priced",
    salePriceCop: 320000,
    withAccessoriesSalePriceCop: 345000,
  },
  {
    id: "ip-camera-ipc-d140h-2-8mm-c",
    brand: "HiLook",
    reference: "IPC-D140H (2.8mm)(C)",
    systemType: "ip",
    resolutionGroup: "4-mp",
    format: "Domo",
    description: "4 MP; H.265+; PoE; IR 30 m; IP67; IK10",
    pricingStatus: "priced",
    salePriceCop: 335000,
    withAccessoriesSalePriceCop: 360000,
  },
  {
    id: "ip-camera-ipc-d640h-z-2-8-12mm-c",
    brand: "HiLook",
    reference: "IPC-D640H-Z (2.8-12mm)(C)",
    systemType: "ip",
    resolutionGroup: "4-mp",
    format: "Domo",
    description: "4 MP; varifocal motorizada; H.265+; IR 30 m; IP67",
    pricingStatus: "priced",
    salePriceCop: 410000,
    withAccessoriesSalePriceCop: 435000,
  },
  {
    id: "ip-camera-dh-ipc-ebw5641p-as",
    brand: "Dahua",
    reference: "DH-IPC-EBW5641P-AS",
    systemType: "ip",
    resolutionGroup: "5-8-mp",
    format: "Ojo de pez",
    description: "6 MP; 360 grados; PoE; micrófono; IR 15 m; IK10",
    pricingStatus: "priced",
    salePriceCop: 980000,
    withAccessoriesSalePriceCop: 1005000,
  },
  {
    id: "ip-camera-ds-2cd2955fwd-i",
    brand: "Hikvision",
    reference: "DS-2CD2955FWD-I",
    systemType: "ip",
    resolutionGroup: "5-8-mp",
    format: "Ojo de pez",
    description: "5 MP; panorámica 180/360; H.265+; WDR; IR 8 m",
    pricingStatus: "priced",
    salePriceCop: 1180000,
    withAccessoriesSalePriceCop: 1205000,
  },
  {
    id: "ip-camera-ds-2cd1063g2-liuf-2-8mm",
    brand: "Hikvision",
    reference: "DS-2CD1063G2-LIUF(2.8mm)",
    systemType: "ip",
    resolutionGroup: "5-8-mp",
    format: "Bala",
    description: "6 MP; Dual Light; micrófono; IR 30 m; luz 20 m",
    pricingStatus: "priced",
    salePriceCop: 495000,
    withAccessoriesSalePriceCop: 520000,
  },
  {
    id: "ip-camera-ds-2cd1163g2-liuf-2-8mm",
    brand: "Hikvision",
    reference: "DS-2CD1163G2-LIUF(2.8mm)",
    systemType: "ip",
    resolutionGroup: "5-8-mp",
    format: "Domo",
    description: "6 MP; Dual Light; micrófono; IR 30 m; luz 20 m",
    pricingStatus: "priced",
    salePriceCop: 515000,
    withAccessoriesSalePriceCop: 540000,
  },
  {
    id: "ip-camera-ds-2cd2183g2-iu-2-8mm",
    brand: "Hikvision",
    reference: "DS-2CD2183G2-IU(2.8mm)",
    systemType: "ip",
    resolutionGroup: "5-8-mp",
    format: "Domo",
    description: "8 MP; WDR; IP67; antivandálica; AcuSense",
    pricingStatus: "priced",
    salePriceCop: 800000,
    withAccessoriesSalePriceCop: 825000,
  },
  {
    id: "ip-camera-ds-2cd2683g2-izs-2-8-12mm",
    brand: "Hikvision",
    reference: "DS-2CD2683G2-IZS(2.8-12mm)",
    systemType: "ip",
    resolutionGroup: "5-8-mp",
    format: "Bala",
    description: "8 MP; varifocal motorizada; IR 60 m; IP67; AcuSense",
    pricingStatus: "priced",
    salePriceCop: 1410000,
    withAccessoriesSalePriceCop: 1435000,
  },
  {
    id: "ip-camera-ds-2cd2783g2-izs-2-8-12mm",
    brand: "Hikvision",
    reference: "DS-2CD2783G2-IZS(2.8-12mm)",
    systemType: "ip",
    resolutionGroup: "5-8-mp",
    format: "Domo",
    description: "8 MP; varifocal motorizada; IR 40 m; IP67; AcuSense",
    pricingStatus: "priced",
    salePriceCop: 1410000,
    withAccessoriesSalePriceCop: 1435000,
  },
] as const satisfies readonly Camera[]);
