import { freezeCatalog, type Recorder } from "./catalog-types";

export const NVR_CATALOG = freezeCatalog([
  {
    id: "nvr-dhi-nvr1104hs-p-s3h-v2",
    brand: "Dahua",
    reference: "DHI-NVR1104HS-P-S3H-V2",
    recorderType: "nvr",
    systemType: "ip",
    channels: 4,
    description: "4 PoE; H.265+; 1 SATA; 80 Mbps; decodificación hasta 6 MP",
    pricingStatus: "priced",
    salePriceCop: 475000,
    poePorts: 4,
  },
  {
    id: "nvr-ds-7104ni-q1-c",
    brand: "Hikvision",
    reference: "DS-7104NI-Q1 (C)",
    recorderType: "nvr",
    systemType: "ip",
    channels: 4,
    description: "Sin PoE; hasta 4 MP; 1 bahía / 6 TB; 60 Mbps; H.265+",
    pricingStatus: "priced",
    salePriceCop: 290000,
    poePorts: 0,
  },
  {
    id: "nvr-ds-7104ni-q1-4p-c",
    brand: "Hikvision",
    reference: "DS-7104NI-Q1/4P (C)",
    recorderType: "nvr",
    systemType: "ip",
    channels: 4,
    description: "4 PoE; 2 MP; 1 bahía / 6 TB; 40 Mbps; H.265+",
    pricingStatus: "priced",
    salePriceCop: 465000,
    poePorts: 4,
  },
  {
    id: "nvr-ds-7604ni-q1-4p-std-d",
    brand: "Hikvision",
    reference: "DS-7604NI-Q1/4P(STD)(D)",
    recorderType: "nvr",
    systemType: "ip",
    channels: 4,
    description: "4 PoE; 2 bahías / 6 TB; 60 Mbps; H.265+",
    pricingStatus: "priced",
    salePriceCop: 680000,
    poePorts: 4,
  },
  {
    id: "nvr-nvr-104mh-c",
    brand: "HiLook",
    reference: "NVR-104MH-C",
    recorderType: "nvr",
    systemType: "ip",
    channels: 4,
    description: "Sin PoE; hasta 8 MP; 1 bahía / 6 TB; H.265+",
    pricingStatus: "priced",
    salePriceCop: 420000,
    poePorts: 0,
  },
  {
    id: "nvr-nvr-104mh-d-4p",
    brand: "HiLook",
    reference: "NVR-104MH-D/4P",
    recorderType: "nvr",
    systemType: "ip",
    channels: 4,
    description: "4 PoE; 4 MP; 1 bahía / 6 TB; 40 Mbps; H.265+",
    pricingStatus: "priced",
    salePriceCop: 485000,
    poePorts: 4,
  },
  {
    id: "nvr-nvr-104mh-c-4p",
    brand: "HiLook",
    reference: "NVR-104MH-C/4P",
    recorderType: "nvr",
    systemType: "ip",
    channels: 4,
    description: "4 PoE; hasta 8 MP; 1 bahía / 6 TB; 40 Mbps",
    pricingStatus: "priced",
    salePriceCop: 610000,
    poePorts: 4,
  },
  {
    id: "nvr-dhi-nvr1108hs-8p-s3h",
    brand: "Dahua",
    reference: "DHI-NVR1108HS-8P-S3H",
    recorderType: "nvr",
    systemType: "ip",
    channels: 8,
    description: "8 PoE; H.265+; 1 SATA; 80 Mbps; decodificación hasta 6 MP",
    pricingStatus: "priced",
    salePriceCop: 640000,
    poePorts: 8,
  },
  {
    id: "nvr-ds-7108ni-q1-8p-c",
    brand: "Hikvision",
    reference: "DS-7108NI-Q1/8P (C)",
    recorderType: "nvr",
    systemType: "ip",
    channels: 8,
    description: "8 PoE; 2 MP; 1 bahía / 6 TB; 60 Mbps; H.265+",
    pricingStatus: "priced",
    salePriceCop: 640000,
    poePorts: 8,
  },
  {
    id: "nvr-ds-7608ni-k2",
    brand: "Hikvision",
    reference: "DS-7608NI-K2",
    recorderType: "nvr",
    systemType: "ip",
    channels: 8,
    description: "Sin PoE; 2 bahías / 6 TB; 80 Mbps; H.265+",
    pricingStatus: "priced",
    salePriceCop: 660000,
    poePorts: 0,
  },
  {
    id: "nvr-ds-7608ni-q1-8p",
    brand: "Hikvision",
    reference: "DS-7608NI-Q1/8P",
    recorderType: "nvr",
    systemType: "ip",
    channels: 8,
    description: "8 PoE; hasta 8 MP; 1 bahía / 6 TB; HDMI 4K",
    pricingStatus: "priced",
    salePriceCop: 890000,
    poePorts: 8,
  },
  {
    id: "nvr-ds-7608ni-q2-8p",
    brand: "Hikvision",
    reference: "DS-7608NI-Q2/8P",
    recorderType: "nvr",
    systemType: "ip",
    channels: 8,
    description: "8 PoE; hasta 8 MP; 2 bahías / 6 TB; HDMI 4K",
    pricingStatus: "priced",
    salePriceCop: 950000,
    poePorts: 8,
  },
  {
    id: "nvr-ds-7608nxi-k2-8p",
    brand: "Hikvision",
    reference: "DS-7608NXI-K2/8P",
    recorderType: "nvr",
    systemType: "ip",
    channels: 8,
    description: "8 PoE; hasta 12 MP; H.265+; HDMI 4K; AcuSense",
    pricingStatus: "priced",
    salePriceCop: 1110000,
    poePorts: 8,
  },
  {
    id: "nvr-nvr-108h-d-8p",
    brand: "HiLook",
    reference: "NVR-108H-D/8P",
    recorderType: "nvr",
    systemType: "ip",
    channels: 8,
    description: "8 PoE; 4 MP; 1 bahía / 6 TB; 80 Mbps; H.265+",
    pricingStatus: "priced",
    salePriceCop: 610000,
    poePorts: 8,
  },
  {
    id: "nvr-nvr-108mh-c-8p",
    brand: "HiLook",
    reference: "NVR-108MH-C/8P",
    recorderType: "nvr",
    systemType: "ip",
    channels: 8,
    description: "8 PoE; hasta 8 MP; 1 bahía / 6 TB; H.265+",
    pricingStatus: "priced",
    salePriceCop: 840000,
    poePorts: 8,
  },
  {
    id: "nvr-ds-7716ni-q4",
    brand: "Hikvision",
    reference: "DS-7716NI-Q4",
    recorderType: "nvr",
    systemType: "ip",
    channels: 16,
    description: "Sin PoE; hasta 8 MP; 4 bahías / 6 TB; H.265+",
    pricingStatus: "priced",
    salePriceCop: 1200000,
    poePorts: 0,
  },
  {
    id: "nvr-ds-7616ni-q2-16p-std-d",
    brand: "Hikvision",
    reference: "DS-7616NI-Q2/16P(STD)(D)",
    recorderType: "nvr",
    systemType: "ip",
    channels: 16,
    description: "16 PoE; 4K; 2 bahías / 6 TB; 160 Mbps; H.265+",
    pricingStatus: "priced",
    salePriceCop: 1330000,
    poePorts: 16,
  },
  {
    id: "nvr-ds-7616ni-k2-16p",
    brand: "Hikvision",
    reference: "DS-7616NI-K2/16P",
    recorderType: "nvr",
    systemType: "ip",
    channels: 16,
    description: "16 PoE; 4K; 2 bahías / 6 TB; 160 Mbps; H.265+",
    pricingStatus: "priced",
    salePriceCop: 1430000,
    poePorts: 16,
  },
  {
    id: "nvr-ds-7616nxi-k2-16p",
    brand: "Hikvision",
    reference: "DS-7616NXI-K2/16P",
    recorderType: "nvr",
    systemType: "ip",
    channels: 16,
    description: "16 PoE; 4K; 160 Mbps; 10 TB; AcuSense",
    pricingStatus: "priced",
    salePriceCop: 1500000,
    poePorts: 16,
  },
  {
    id: "nvr-ds-7716ni-q4-16p",
    brand: "Hikvision",
    reference: "DS-7716NI-Q4/16P",
    recorderType: "nvr",
    systemType: "ip",
    channels: 16,
    description: "16 PoE; hasta 8 MP; 4 bahías / 6 TB; H.265+",
    pricingStatus: "priced",
    salePriceCop: 1870000,
    poePorts: 16,
  },
  {
    id: "nvr-nvr-216mh-c-16p",
    brand: "HiLook",
    reference: "NVR-216MH-C/16P",
    recorderType: "nvr",
    systemType: "ip",
    channels: 16,
    description: "16 PoE; 4K; 2 bahías / 6 TB; H.265+",
    pricingStatus: "priced",
    salePriceCop: 1310000,
    poePorts: 16,
  },
  {
    id: "nvr-dhi-nvr4232-4ks3",
    brand: "Dahua",
    reference: "DHI-NVR4232-4KS3",
    recorderType: "nvr",
    systemType: "ip",
    channels: 32,
    description: "Sin PoE; H.265; 2 SATA; 200 Mbps; decodificación 2 x 4K",
    pricingStatus: "priced",
    salePriceCop: 1090000,
    poePorts: 0,
  },
  {
    id: "nvr-ds-7732ni-k4",
    brand: "Hikvision",
    reference: "DS-7732NI-K4",
    recorderType: "nvr",
    systemType: "ip",
    channels: 32,
    description: "Sin PoE; hasta 8 MP; 4 bahías / 6 TB; 256 Mbps",
    pricingStatus: "priced",
    salePriceCop: 1650000,
    poePorts: 0,
  },
  {
    id: "nvr-ds-7732nxi-k4",
    brand: "Hikvision",
    reference: "DS-7732NXI-K4",
    recorderType: "nvr",
    systemType: "ip",
    channels: 32,
    description: "Sin PoE; hasta 12 MP; 256 Mbps; 4K; AcuSense",
    pricingStatus: "priced",
    salePriceCop: 1930000,
    poePorts: 0,
  },
  {
    id: "nvr-ds-7732ni-k4-16p",
    brand: "Hikvision",
    reference: "DS-7732NI-K4/16P",
    recorderType: "nvr",
    systemType: "ip",
    channels: 32,
    description: "16 PoE+; hasta 8 MP; 4 bahías / 6 TB; alcance 300 m",
    pricingStatus: "priced",
    salePriceCop: 2450000,
    poePorts: 16,
  },
  {
    id: "nvr-ds-7732nxi-k4-16p",
    brand: "Hikvision",
    reference: "DS-7732NXI-K4/16P",
    recorderType: "nvr",
    systemType: "ip",
    channels: 32,
    description: "16 PoE; hasta 12 MP; reconocimiento facial; AcuSense",
    pricingStatus: "priced",
    salePriceCop: 2570000,
    poePorts: 16,
  },
] as const satisfies readonly Recorder[]);
