import { freezeCatalog, type PoeSwitch } from "./catalog-types";

export const POE_SWITCH_CATALOG = freezeCatalog([
  {
    id: "poe-switch-ds-3e0105p-e-m",
    brand: "Hikvision",
    reference: "DS-3E0105P-E/M",
    poePorts: 4,
    description: "10/100 Mbps; 1 uplink; 35 W; metálico",
    pricingStatus: "priced",
    salePriceCop: 180000,
  },
  {
    id: "poe-switch-ds-3e0106p-e-m",
    brand: "Hikvision",
    reference: "DS-3E0106P-E/M",
    poePorts: 4,
    description: "10/100 Mbps; 2 uplink; 35 W; metálico",
    pricingStatus: "priced",
    salePriceCop: 225000,
  },
  {
    id: "poe-switch-ds-3e0109p-e-m",
    brand: "Hikvision",
    reference: "DS-3E0109P-E/M",
    poePorts: 8,
    description: "10/100 Mbps; 1 uplink; 60 W; metálico",
    pricingStatus: "priced",
    salePriceCop: 255000,
  },
  {
    id: "poe-switch-ds-3e0505p-e-m",
    brand: "Hikvision",
    reference: "DS-3E0505P-E/M",
    poePorts: 4,
    description: "Gigabit PoE+; 1 uplink gigabit; 35 W",
    pricingStatus: "priced",
    salePriceCop: 240000,
  },
  {
    id: "poe-switch-ds-3e0510p-e-m",
    brand: "Hikvision",
    reference: "DS-3E0510P-E/M",
    poePorts: 8,
    description: "Gigabit PoE; 1 puerto SFP",
    pricingStatus: "priced",
    salePriceCop: 415000,
  },
  {
    id: "poe-switch-ds-3e0318p-e-m-b",
    brand: "Hikvision",
    reference: "DS-3E0318P-E/M(B)",
    poePorts: 16,
    description: "10/100 Mbps; 130 W; metálico",
    pricingStatus: "priced",
    salePriceCop: 870000,
  },
  {
    id: "poe-switch-ds-3e0326p-e-m-c",
    brand: "Hikvision",
    reference: "DS-3E0326P-E/M(C)",
    poePorts: 24,
    description: "10/100 Mbps; 230 W; metálico",
    pricingStatus: "priced",
    salePriceCop: 1050000,
  },
  {
    id: "poe-switch-ds-3e0526p-e-m",
    brand: "Hikvision",
    reference: "DS-3E0526P-E/M",
    poePorts: 24,
    description: "Gigabit PoE; no administrable; 225 W; 2 SFP",
    pricingStatus: "priced",
    salePriceCop: 1390000,
  },
  {
    id: "poe-switch-wk-ps206v2",
    brand: "Witek",
    reference: "WK-PS206V2",
    poePorts: 4,
    description: "10/100 Mbps; 2 uplink",
    pricingStatus: "priced",
    salePriceCop: 95000,
  },
  {
    id: "poe-switch-wk-ps210v2",
    brand: "Witek",
    reference: "WK-PS210V2",
    poePorts: 8,
    description: "10/100 Mbps; 2 uplink",
    pricingStatus: "priced",
    salePriceCop: 140000,
  },
  {
    id: "poe-switch-wk-ps219gf",
    brand: "Witek",
    reference: "WK-PS219GF",
    poePorts: 16,
    description: "10/100 Mbps; 2 uplink gigabit; 1 SFP",
    pricingStatus: "priced",
    salePriceCop: 400000,
  },
  {
    id: "poe-switch-wk-ps227gf",
    brand: "Witek",
    reference: "WK-PS227GF",
    poePorts: 24,
    description: "10/100 Mbps; 2 uplink gigabit; 1 SFP",
    pricingStatus: "priced",
    salePriceCop: 530000,
  },
  {
    id: "poe-switch-wk-ps305v2",
    brand: "Witek",
    reference: "WK-PS305V2",
    poePorts: 4,
    description: "Gigabit PoE; 1 uplink gigabit",
    pricingStatus: "priced",
    salePriceCop: 135000,
  },
  {
    id: "poe-switch-wk-ps310v2",
    brand: "Witek",
    reference: "WK-PS310V2",
    poePorts: 8,
    description: "Gigabit PoE; 2 uplink gigabit",
    pricingStatus: "priced",
    salePriceCop: 205000,
  },
] as const satisfies readonly PoeSwitch[]);
