import { freezeCatalog, type Camera } from "./catalog-types";

export const WIFI_CAMERA_CATALOG = freezeCatalog([
  {
    id: "wifi-camera-dh-ipc-h3ap-0360b",
    brand: "Dahua",
    reference: "DH-IPC-H3AP-0360B",
    systemType: "wifi",
    resolutionGroup: "3-mp-2k",
    format: "Cubo",
    description: "3 MP / 2K; Wi-Fi 2,4 GHz; IR 10 m; audio 2 vías",
    pricingStatus: "priced",
    salePriceCop: 130000,
    withAccessoriesSalePriceCop: 145000,
  },
  {
    id: "wifi-camera-dh-ipc-h5ap-0360b",
    brand: "Dahua",
    reference: "DH-IPC-H5AP-0360B",
    systemType: "wifi",
    resolutionGroup: "5-mp",
    format: "Cubo",
    description: "5 MP; Wi-Fi 2,4 GHz; IR 10 m; audio 2 vías",
    pricingStatus: "priced",
    salePriceCop: 170000,
    withAccessoriesSalePriceCop: 185000,
  },
  {
    id: "wifi-camera-dh-ipc-t3ap-pv-0280b",
    brand: "Dahua",
    reference: "DH-IPC-T3AP-PV-0280B",
    systemType: "wifi",
    resolutionGroup: "3-mp",
    format: "Turret",
    description: "3 MP; Full Color; detección; audio 2 vías; IP67",
    pricingStatus: "priced",
    salePriceCop: 260000,
    withAccessoriesSalePriceCop: 280000,
  },
  {
    id: "wifi-camera-dh-ipc-f3dp-pv-0280b",
    brand: "Dahua",
    reference: "DH-IPC-F3DP-PV-0280B",
    systemType: "wifi",
    resolutionGroup: "3-mp",
    format: "Bala",
    description: "3 MP; Wi-Fi 2,4 GHz; Dual Light; micrófono; IP67",
    pricingStatus: "priced",
    salePriceCop: 245000,
    withAccessoriesSalePriceCop: 265000,
  },
  {
    id: "wifi-camera-dh-ipc-f5dp-il-0280b",
    brand: "Dahua",
    reference: "DH-IPC-F5DP-IL-0280B",
    systemType: "wifi",
    resolutionGroup: "5-mp",
    format: "Bala",
    description: "5 MP; Wi-Fi 2,4 GHz; Dual Light; micrófono; IP67",
    pricingStatus: "priced",
    salePriceCop: 250000,
    withAccessoriesSalePriceCop: 270000,
  },
  {
    id: "wifi-camera-dh-ipc-h3dp-3f-0360b",
    brand: "Dahua",
    reference: "DH-IPC-H3DP-3F-0360B",
    systemType: "wifi",
    resolutionGroup: "6-mp-combined",
    format: "Dual PT",
    description: "6 MP combinados; Wi-Fi 6; Full Color; audio 2 vías",
    pricingStatus: "priced",
    salePriceCop: 270000,
    withAccessoriesSalePriceCop: 285000,
  },
  {
    id: "wifi-camera-dh-ipc-h5dp-5f-0360b",
    brand: "Dahua",
    reference: "DH-IPC-H5DP-5F-0360B",
    systemType: "wifi",
    resolutionGroup: "10-mp-combined",
    format: "Dual PT",
    description: "10 MP combinados; Wi-Fi 6; Full Color; audio 2 vías",
    pricingStatus: "priced",
    salePriceCop: 300000,
    withAccessoriesSalePriceCop: 315000,
  },
  {
    id: "wifi-camera-dh-ipc-p3asp-pv-0400b-s2",
    brand: "Dahua",
    reference: "DH-IPC-P3ASP-PV-0400B-S2",
    systemType: "wifi",
    resolutionGroup: "3-mp-2k",
    format: "PT",
    description: "3 MP / 2K; Wi-Fi 6; seguimiento; audio 2 vías",
    pricingStatus: "priced",
    salePriceCop: 245000,
    withAccessoriesSalePriceCop: 260000,
  },
  {
    id: "wifi-camera-dh-ipc-p5asp-pv-0400b-s2",
    brand: "Dahua",
    reference: "DH-IPC-P5ASP-PV-0400B-S2",
    systemType: "wifi",
    resolutionGroup: "5-mp",
    format: "PT",
    description: "5 MP; Wi-Fi 6; seguimiento; audio 2 vías",
    pricingStatus: "priced",
    salePriceCop: 280000,
    withAccessoriesSalePriceCop: 295000,
  },
  {
    id: "wifi-camera-dh-ipc-p3dp-3f-pv",
    brand: "Dahua",
    reference: "DH-IPC-P3DP-3F-PV",
    systemType: "wifi",
    resolutionGroup: "6-mp-combined",
    format: "Dual PT",
    description: "6 MP combinados; Wi-Fi 6; Full Color; audio 2 vías; IP66",
    pricingStatus: "priced",
    salePriceCop: 330000,
    withAccessoriesSalePriceCop: 350000,
  },
  {
    id: "wifi-camera-dh-ipc-p5dp-5f-pv",
    brand: "Dahua",
    reference: "DH-IPC-P5DP-5F-PV",
    systemType: "wifi",
    resolutionGroup: "10-mp-combined",
    format: "Dual PT",
    description: "10 MP combinados; Wi-Fi 6; Full Color; audio 2 vías; IP66",
    pricingStatus: "priced",
    salePriceCop: 375000,
    withAccessoriesSalePriceCop: 395000,
  },
  {
    id: "wifi-camera-ds-2cd2423g2-iw-w",
    brand: "Hikvision",
    reference: "DS-2CD2423G2-IW (W)",
    systemType: "wifi",
    resolutionGroup: "2-mp",
    format: "Cubo",
    description: "2 MP; Wi-Fi; micrófono; AcuSense; Hik-Connect",
    pricingStatus: "priced",
    salePriceCop: 190000,
    withAccessoriesSalePriceCop: 205000,
  },
  {
    id: "wifi-camera-ds-2cv2q21g1-idw-w",
    brand: "Hikvision",
    reference: "DS-2CV2Q21G1-IDW (W)",
    systemType: "wifi",
    resolutionGroup: "2-mp",
    format: "PT",
    description: "2 MP; Wi-Fi; Motion 2.0; detección humana; interior",
    pricingStatus: "priced",
    salePriceCop: 185000,
    withAccessoriesSalePriceCop: 200000,
  },
  {
    id: "wifi-camera-ds-2de2c400iwg-w-2-8mm",
    brand: "Hikvision",
    reference: "DS-2DE2C400IWG/W(2.8mm)",
    systemType: "wifi",
    resolutionGroup: "4-mp",
    format: "PT",
    description: "4 MP; Wi-Fi; audio 2 vías; microSD 512 GB; exterior",
    pricingStatus: "priced",
    salePriceCop: 375000,
    withAccessoriesSalePriceCop: 395000,
  },
  {
    id: "wifi-camera-ds-2cv2021g2-idw-2-8mm",
    brand: "Hikvision",
    reference: "DS-2CV2021G2-IDW(2.8mm)",
    systemType: "wifi",
    resolutionGroup: "2-mp",
    format: "Bala",
    description: "2 MP; Wi-Fi; audio; Hik-Connect; exterior",
    pricingStatus: "priced",
    salePriceCop: 210000,
    withAccessoriesSalePriceCop: 230000,
  },
  {
    id: "wifi-camera-ds-2cv2041g2-idw-2-8mm",
    brand: "Hikvision",
    reference: "DS-2CV2041G2-IDW(2.8mm)",
    systemType: "wifi",
    resolutionGroup: "4-mp",
    format: "Bala",
    description: "4 MP; Wi-Fi; audio; Hik-Connect; exterior",
    pricingStatus: "priced",
    salePriceCop: 265000,
    withAccessoriesSalePriceCop: 285000,
  },
  {
    id: "wifi-camera-ds-2cd2421g0-iw-2-8mm-w",
    brand: "Hikvision",
    reference: "DS-2CD2421G0-IW(2.8mm)(W)",
    systemType: "wifi",
    resolutionGroup: "2-mp",
    format: "Cubo",
    description: "2 MP; Wi-Fi; PoE; audio 2 vías; IR 10 m; microSD",
    pricingStatus: "priced",
    salePriceCop: 375000,
    withAccessoriesSalePriceCop: 390000,
  },
  {
    id: "wifi-camera-ds-2cd2443g0-iw-2-8mm-w",
    brand: "Hikvision",
    reference: "DS-2CD2443G0-IW(2.8mm)(W)",
    systemType: "wifi",
    resolutionGroup: "4-mp",
    format: "Cubo",
    description: "4 MP; Wi-Fi; audio 2 vías; IR 10 m; microSD",
    pricingStatus: "priced",
    salePriceCop: 550000,
    withAccessoriesSalePriceCop: 565000,
  },
  {
    id: "wifi-camera-ipc-p220-d-w-4mm-b",
    brand: "HiLook",
    reference: "IPC-P220-D/W(4mm)B",
    systemType: "wifi",
    resolutionGroup: "2-mp",
    format: "PT",
    description: "2 MP; Wi-Fi residencial; IR 10 m; microSD; interior",
    pricingStatus: "priced",
    salePriceCop: 190000,
    withAccessoriesSalePriceCop: 205000,
  },
] as const satisfies readonly Camera[]);
